# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /.devcontainer
    schedule:
      interval: daily
